name: Code Coverage

on:
  pull_request:
    branches: [dev]
  workflow_dispatch:

jobs:
  coverage:
    uses: OpenVoiceOS/gh-automations/.github/workflows/coverage.yml@dev
    secrets: inherit
    with:
      python_version: '3.11'
      coverage_source: 'hivemind_core'
      test_path: 'test/'
      install_extras: ''
      min_coverage: 0
