name: License Check

on:
  push:
    branches: [dev, master]
  pull_request:
    branches: [dev, master]

jobs:
  license-check:
    uses: OpenVoiceOS/gh-automations/.github/workflows/license-check.yml@dev
