name: Lint

on:
  pull_request:
    branches: [dev, master, main]
  workflow_dispatch:

jobs:
  lint:
    uses: OpenVoiceOS/gh-automations/.github/workflows/lint.yml@dev
    with:
      ruff: true
      pre_commit: false   # set true if .pre-commit-config.yaml exists
      pr_comment: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name == github.repository }}
