name: Publish Stable Release

on:
  workflow_dispatch:
  push:
    branches: [master]

permissions:
  contents: write

jobs:
  publish_stable:
    uses: OpenVoiceOS/gh-automations/.github/workflows/publish-stable.yml@dev
    secrets:
      PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
      MATRIX_TOKEN: ${{ secrets.MATRIX_TOKEN }}
    with:
      version_file: 'hivemind_core/version.py'
      publish_pypi: true
      notify_matrix: false
