name: Release Alpha and Propose Stable
on:
  pull_request:
    types: [closed]
    branches: [dev]

jobs:
  publish_alpha:
    uses: OpenVoiceOS/gh-automations/.github/workflows/publish-alpha.yml@dev
    secrets: inherit
    with:
      branch: 'dev'
      version_file: 'hivemind_core/version.py'
      update_changelog: true
      publish_prerelease: true
      publish_pypi: true
      changelog_max_issues: 100
