name: Repo Health

on:
  pull_request:
    branches: [dev, master, main]
  workflow_dispatch:

jobs:
  repo_health:
    uses: OpenVoiceOS/gh-automations/.github/workflows/repo-health.yml@dev
    secrets: inherit
    with:
      version_file: 'hivemind_core/version.py'
